// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flowexec/flow/internal/cache (interfaces: ExecutableCache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_executable_cache.go -package=mocks github.com/flowexec/flow/internal/cache ExecutableCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	executable "github.com/flowexec/flow/types/executable"
	io "github.com/flowexec/tuikit/io"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutableCache is a mock of ExecutableCache interface.
type MockExecutableCache struct {
	ctrl     *gomock.Controller
	recorder *MockExecutableCacheMockRecorder
}

// MockExecutableCacheMockRecorder is the mock recorder for MockExecutableCache.
type MockExecutableCacheMockRecorder struct {
	mock *MockExecutableCache
}

// NewMockExecutableCache creates a new mock instance.
func NewMockExecutableCache(ctrl *gomock.Controller) *MockExecutableCache {
	mock := &MockExecutableCache{ctrl: ctrl}
	mock.recorder = &MockExecutableCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutableCache) EXPECT() *MockExecutableCacheMockRecorder {
	return m.recorder
}

// GetExecutableByRef mocks base method.
func (m *MockExecutableCache) GetExecutableByRef(arg0 io.Logger, arg1 executable.Ref) (*executable.Executable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutableByRef", arg0, arg1)
	ret0, _ := ret[0].(*executable.Executable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutableByRef indicates an expected call of GetExecutableByRef.
func (mr *MockExecutableCacheMockRecorder) GetExecutableByRef(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutableByRef", reflect.TypeOf((*MockExecutableCache)(nil).GetExecutableByRef), arg0, arg1)
}

// GetExecutableList mocks base method.
func (m *MockExecutableCache) GetExecutableList(arg0 io.Logger) (executable.ExecutableList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutableList", arg0)
	ret0, _ := ret[0].(executable.ExecutableList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutableList indicates an expected call of GetExecutableList.
func (mr *MockExecutableCacheMockRecorder) GetExecutableList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutableList", reflect.TypeOf((*MockExecutableCache)(nil).GetExecutableList), arg0)
}

// Update mocks base method.
func (m *MockExecutableCache) Update(arg0 io.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExecutableCacheMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExecutableCache)(nil).Update), arg0)
}
