name: Bug Report
description: File a bug report
labels: [bug, triage]
#assignees:
#  - jahvon
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is. What happened, and what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add
    validations:
      required: false
