// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package executable

// File source and destination configuration.
// Go templating from form data is supported in all fields.
type Artifact struct {
	// If true, the artifact will be copied as a template file. The file will be
	// rendered using Go templating from
	// the form data. [Sprig functions](https://masterminds.github.io/sprig/) are
	// available for use in the template.
	//
	AsTemplate bool `json:"asTemplate,omitempty" yaml:"asTemplate,omitempty" mapstructure:"asTemplate,omitempty"`

	// The directory to copy the file to. If not set, the file will be copied to the
	// root of the flow file directory.
	// The directory will be created if it does not exist.
	//
	DstDir *string `json:"dstDir,omitempty" yaml:"dstDir,omitempty" mapstructure:"dstDir,omitempty"`

	// The name of the file to copy to. If not set, the file will be copied with the
	// same name.
	DstName string `json:"dstName,omitempty" yaml:"dstName,omitempty" mapstructure:"dstName,omitempty"`

	// A condition to determine if the artifact should be copied. The condition is
	// evaluated using Go templating
	// from the form data. If the condition is not met, the artifact will not be
	// copied.
	// [Sprig functions](https://masterminds.github.io/sprig/) are available for use
	// in the condition.
	//
	// For example, to copy the artifact only if the `name` field is set:
	// ```
	// {{ if .name }}true{{ end }}
	// ```
	//
	If string `json:"if,omitempty" yaml:"if,omitempty" mapstructure:"if,omitempty"`

	// The directory to copy the file from.
	// If not set, the file will be copied from the directory of the template file.
	//
	SrcDir string `json:"srcDir,omitempty" yaml:"srcDir,omitempty" mapstructure:"srcDir,omitempty"`

	// The name of the file to copy.
	SrcName string `json:"srcName" yaml:"srcName" mapstructure:"srcName"`
}

// A field to be displayed to the user when generating a flow file from a template.
type Field struct {
	// The default value to use if a value is not set.
	Default string `json:"default,omitempty" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// A description of the field.
	Description string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// The key to associate the data with. This is used as the key in the template
	// data map.
	Key string `json:"key" yaml:"key" mapstructure:"key"`

	// A prompt to be displayed to the user when collecting an input value.
	Prompt string `json:"prompt" yaml:"prompt" mapstructure:"prompt"`

	// If true, a value must be set. If false, the default value will be used if a
	// value is not set.
	Required bool `json:"required,omitempty" yaml:"required,omitempty" mapstructure:"required,omitempty"`

	// A regular expression to validate the input value against.
	Validate string `json:"validate,omitempty" yaml:"validate,omitempty" mapstructure:"validate,omitempty"`

	// value corresponds to the JSON schema field "value".
	value *string `json:"value,omitempty" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// Configuration for a flowfile template; templates can be used to generate flow
// files.
type Template struct {
	// A list of artifacts to be copied after generating the flow file.
	Artifacts []Artifact `json:"artifacts,omitempty" yaml:"artifacts,omitempty" mapstructure:"artifacts,omitempty"`

	// Form fields to be displayed to the user when generating a flow file from a
	// template.
	// The form will be rendered first, and the user's input can be used to render the
	// template.
	// For example, a form field with the key `name` can be used in the template as
	// `{{.name}}`.
	//
	Form []Field `json:"form,omitempty" yaml:"form,omitempty" mapstructure:"form,omitempty"`

	// A list of exec executables to run after generating the flow file.
	PostRun []TemplatePostRunElem `json:"postRun,omitempty" yaml:"postRun,omitempty" mapstructure:"postRun,omitempty"`

	// A list of exec executables to run before generating the flow file.
	PreRun []TemplatePreRunElem `json:"preRun,omitempty" yaml:"preRun,omitempty" mapstructure:"preRun,omitempty"`

	// The flow file template to generate. The template must be a valid flow file
	// after rendering.
	Template string `json:"template" yaml:"template" mapstructure:"template"`
}

type TemplatePostRunElem ExecExecutableType

type TemplatePreRunElem ExecExecutableType
