// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config

type Entry struct {
	// Config corresponds to the JSON schema field "config".
	Config EntryConfig `koanf:"config"`

	// Provider corresponds to the JSON schema field "provider".
	Provider EntryProvider `koanf:"provider"`
}

type EntryConfig map[string]interface{}

type EntryProvider string

const EntryProviderCli EntryProvider = "cli"
const EntryProviderDefault EntryProvider = "default"

// User Configuration for the flow CLI vaults.
type Vault struct {
	// The name of the active vault. This should match a key in the `vaults` map.
	Current string `koanf:"current"`

	// A list of vaults that can be used to store secrets.
	Vaults VaultVaults `koanf:"vaults"`
}

// A list of vaults that can be used to store secrets.
type VaultVaults map[string]interface{}
